import shutil
import tempfile
from chatbots.search import SearchLocalDatabaseSemantic, NNConfig


__DIXIE_FLATLINE_ARTICLE__ = """
McCoy Pauley aka Dixie Flatline or just Dix is a famous computer hacker who was one of the mentors of Case.

A redneck from the Atlanta fringes. When Case met him, he was a thickset man in shirtsleeves, and his skin had a leaden shade.
As a construct, Dixie was not sure if he was sentient, as he was a bunch of ROM and would not be able to write a poem, but it feels like he is sentient. He said that his existence didn't feel like anything, and compared it like the phantom sensation of an amputated member. Whenever Case communicated with him in the cyberspace, Case felt an odd feeling like "someone reading over your shoulder". Whenever he joked, he released an unpleasant laughter sensation that Case felt in his spine.

During the War he and Elroy ended up in a POW camp in Siberia where they stayed more than a month; he remembered when Elroy still felt a phantom itching on his amputated thumb. Dixie was implanted a surplus Russian heart. After the war he refused to replace it, as its particular beat gave him a sense of timing.
He became a "redneck jockey". He was jacked and larking around at the Rio heavy commerce sector. He picked up a white cubical shape 3 levels higher. He jacked up there and made a pass. From its dense ICE he realised it was an AI. Jacked out, he told his computer to look it up in the Turing Registry, its mainframe owned by Frog company. Like crazy, he returned eager to try to hack it. Hitting the first strata, the Black ICE burned him. His joeboy "smelled the skin frying" and pulled the trodes off him. Being flatlined, it was how he earned his nickname. The grapevine of the hacker scene and in the Gentleman Loser (GL) said that he managed an unspecified impossible feat, maybe a Brazilian payroll net. Despite and because of his legendary status as the "Lazarus of cyberspace" the cowboy elite of the GL shunned him out of superstitious awe.
He met Case in the GL, and trained him in Miami. He even showed the tapes of his EEG to Case. Before his death, Sense/Net paid him a lot to save the contents of his mind onto a ROM and stored it in their library vault in the Sense/Net Pyramid. He died of heart attack when the Russian implant failed him.

Armitage ordered Case and Molly steal the ROM with Dixie's construct and Dixie helps them complete their mission.
Case connected the construct to his computer, after slotting some ice, and jacked in the matrix. The construct was like the sensation of someone reading over his shoulder. Dixie spoke with a directionless voice and remembered Case, but couldn't remember any events before. Case disconnected and reconnected the construct, and when Dixie reappeared he didn't remember the previous discussion. Case said about jacking his ROM personality matrix into the bank with sequential, real time memory, and told him that he is a ROM construct now. Dixie first guided him to a Copenhagen academic grid in order to hijack Bell Europa and sleaze over to London grid and access Armitage's database. Flatline chanted to him some digits, which Case punched on his deck (it took three tries).
Dixie was stored in Case's Hosaka computer and in the meantime he figured out he was dead. From Zion Case connected to the matrix near the Eastern Seaboard Fission Authority pyramid. Asked about his situation, Dixie said that it didn't feel like anything, and he was bothered by the fact that nothing bothered him, comparing it to Elroy's phantom itch. He asked Case as a favor to erase him when everything is over.
While on Marcus Garvey Case jacked in and asked if he ever tried to crack an AI, and Dixie told him about the cube that fried his brain and earned his nickname. Case asked him what about looking at an AI in Berne and Dix said they could do if he isn't afraid to die. Case took them to the Swiss banking sector, and Berne. Dix guided him upwards. They reached a simple cube of white light, and Dix warned him that despite its simple appearance, touching it would be lethal. Case approached and Dix observed the cube surface seething with faint internal shadows, meaning that it sensed their presence. As Case punched forward, a gray circle formed on its face and Dix ordered Case to back off fast. Still, the circle detached as a sphere after them; even as they plunged down a twilit shaft of Swiss banks in max reverse it gained on Case. Dix ordered him to jack out but it was too late, and the AI accessed his brain.
When Case returned, he was asked about Chinese virus programs such as Kuang Grade Mark Eleven which Dixie didn't know a lot of things, but confirmed that a military icebreaker could cut an AI, as told by Case. Case told him that Wintermute was linked to the AI that flatlined him, and wanted his opinion about its motives to burn itself, and get him to shaft Armitage; Dixie said that they can't get a handle on an AI's motive, being no human; he pointed out that although he is a bunch of ROM, it feels like he is sentient, releasing his ugly laughter, and unlike an AI he would not be able to write a poem; he found amusing that a company owns its "brain" and knowledge, but that its "thoughts" have Swiss citizenship. He pointed out that there is no distinction between an AI's moves and its parent company's, but the moment they gain autonomy, the Turing Police wipes it. Finally Case slotted the virus for Dixie to scan its instruction face; after a few secs Dixie said it can crack a military target in some hours, or an AI, "unless you got a morbid fear of dying". With that Case noted that sometimes he repeats himself and Dixie said it's his nature.
Case again accessed Dixie having attached a simple phone link to the Hosaka computer, and his voice was heard through the computer's voice chip, without the carefully engineered accent. Case asked him to punch his way in the Intercontinental, ride in on his phone and do their records to locate Molly's whereabouts. It took him a few minutes to screw their security net deep enough to discover that she was registered as "Rose Kolodny". After some time he found a nightclub that strangely had some weird ICE around it; he got the address and left without leaving a calling card. Case thanked him, telling him to tell the Hosaka to tell Maelcum to disconnect the modem.
The following day the Hosaka patched into a twin bank on Armitage's ship and Flatline knew that the Turing Police caught Case. He made the computer asking for him. Soon Case came to Garvey and Maelcum told him to check "what th' ghost say". Case connected again at the Sikkim sector and told him that Wintermute killed the cops. Dixie warned that more will be coming and probably are listening this grid sector; so Armitage says to make the run now. With a speed and accuracy that Case envied, he executed an intricate series of jumps, and brought them to the Freeside coordinates. He warned Case that Tessier-Ashpool core data is protected by ICE generated by their 2 AI's, comparable to the military, and if he approaches, their tracers will notify the T-A boardroom. Case for a moment offered to bail out, rescue him and let the Turing care, but Dixie reminded him that he would rather check out the Kuang that Armitage had brought him. Indeed, this was enough to change his mind; he loaded the Kuang and jacked in again; as the program unfolded in an enormous form above them, blotting out the void. Dixie said "Big mother". He rented 20" on a little pink box, a commercial unit near the ICE. He told Case that the Kuang is a slow virus that will make them invisible.
Soon after Case had another encounter with Wintermute and Dixie notified him that he was flatlined for 5 seconds.
Later, when the virus grew bigger, Dixie punched them up over the strata. Case noticed a shark in its core, and Dixie said that it is its sting, and they will ride it when the virus interfaces with the ICE. Case confirmed to Dixie that indeed Wintermute has some password switch, that overrides his control hardwiring. Dixie told him that the virus has more time yet and Case jacked out.
"""

__JOHNNY_SILVERHAND_ARTICLE__ = """
They say you can become a legendary rockerboy without all the sex and drugs, the manic depression, run-ins with the law and one toxic relationship after another. But Johnny Silverhand's old school.
Frontman for Samurai, charismatic visionary, rebel with a cause, sworn enemy of corporations (but especially Arasaka) and the mind behind the cult singles "Chippin' In" and "Never Fade Away" - currently residing in V's brain as a digitized tenant.
Silverhand met his demise during the attack on Arasaka Tower after getting shot by Adam Smasher and subsequently flatlined by Soulkiller. But some rockerboys never really die. Point in case - Silverhand's personality construct was kept in Arasaka's labs for decades before it landed on a prototype biochip call the Relic, which - following a series of unexpected events - ended up in V's brain. If you think spending eternity in a cyberspace prison is worse than sharing your headspace with a complete stranger, you'd be dead wrong. For an egomaniac and narcissist like Johnny, it's a living hell.[22]
"""


__RELIC_ARTICLE__ = """
The Relic is a series of Arasaka biochips allowing the storage and manifested reading of digitized human psyches known as engrams.
At least two separate versions of the biochip prototype were developed by 2077, according to the summarized internal report assembled by the former director of the Relic project, Anders Hellman, upon turning coat for the benefit of Arasaka's rival corporation, Kang Tao. 
The first version was intended for the commercial market and advertised as a means for wealthy elites to store their psyche in form of an engram capable of basic communication with their loved ones. The form itself would have consciousness but lack true self-awareness. In spite of its limitations, Relic 1.0 has managed to enter the market and the lives of Night City residents, giving hope by providing a notion of immortality truly approaching human reach. Arasaka logs on the other hand reveal that the Relic's initial purpose was of a more capitalist nature - using Soulkiller on celebrities, important cultural icons and artists in order to create engrams for commercialisation purposes.
The second version of the biochip was a top secret project, personally commissioned and supervised by Saburo Arasaka. It was intended for internal use within the corporation only, never to be sold. Unlike the original biochip, which was only used to communicate with pre-saved engrams with artificially integrated limitations, Relic 2.0 contains a system which was meant to install and activate the engram in a new organic body. The core idea of the project was to implant a digitized psyche into a new host, although only after the body had all neural and cardiac functions terminated, at which point it would automatically expand into the host's brain using nanotechnology. In short, a person who copied their mind onto Relic 2.0 and then died could be restored to life in a new body using the chip, effectively granting them immortality. Internal testing of Relic 2.0 showed promising results, but Arasaka scientists had difficulty preventing the personality construct from becoming emotionally unstable after re-implantation, and the biochip eventually failed in every trial. The Arasaka Corporation also confirmed that Relic 2.0 would not activate if implanted in living individuals who were on the verge of death. The project had not progressed past the trial phase until an unplanned undertaking of the process by a living individual. Examination of the relic's advancement proved that, despite keeping the subject alive, it was continuing its functional expansion and taking over the motor and psychological functions of the host.
The Relic biochip must be stored and transported in stable thermal conditions and in an appropriate neural environment. Even momentary exposure to temperatures falling outside the recommended range could result in permanent damage to the technology. It is currently recommended to store the Relic device in Arasaka laboratory-certified isothermal containers to ensure a stable storage temperature within 2-8 degrees Celsius (35.6-46.4 degrees Fahrenheit).
It is easy to discern that a great majority of people, regardless of closeness to the Secure Your Soul program, treat the Relic as a device that grants immortality. Hanako Arasaka treats the engram of her father as a real human being and the relic as a vessel of his consciousness. Yorinobu Arasaka potentially believed that interrupting the Relic project might prevent his father's resurrection. Liam Northom, the manager and lover of Lizzy Wizzy, had plans for making a backup of her own engram and editing it in order to modify her behaviour.
While Anders Hellman himself never treated the biochip as a device that can actually host consciousness, the contract for the repossession of a human "soul" for the Secure Your Soul program signed under his name promises not to make copies of the created engram due to ethical concerns.
Alt Cunningham, explains that, while she exists as an engram, uploaded to the net, she has no consciousness and effectively poses a role of a rogue AI. She adds that the real Alt died with her organic body once Johnny Silverhand severed the connection between the engram and her consciousness during the 2013 Arasaka raid. As an untethered AI, she is able to read other engrams in their most basic form so regardless of them potentially experiencing a very human thought process, the raw data written this way leaves nothing concealed. On the other hand, the Mikoshi environment allows engrams themselves to interact with one another on a more human level, without the restriction of reading ahead of each other's thoughts, emulating proper conversations.
Similar to all other types of data, engrams can be overwritten with another digitized psyche, which is something Alt offers as a final solution for V's troubles.
"""


__CORTEX_CHIP_ARTICLE__ = """
A Cortex Chip is a type of computer chip designed to store artificial intelligences for robots. Additionally, Cortex Chips appear to be compatible with neurographs.
A Cortex Chip has a universal connector, allowing it to be inserted into machinery, such as robots or an Omnitool.
Cortex Chips seem to come with in-built audio recording and processing software in order to process sounds and voices and interact accordingly. When combined with an Occu-Torch, a Cortex Chip can provide brain scans with visual capabilities. However, Cortex Chips are not designed to handle brain scans, and if loaded with a scan they may overload if the scanned person experiences extreme emotions.
Over the course of his journey, Simon Jarrett encounters several robots, known as Mockingbirds, containing brain scans of PATHOS-II employees, presumably stored on Cortex Chips. Though some are able to communicate with Simon, others are hostile, attacking him on sight.
Simon obtains two Cortex Chips over the course of the game. One contains a brain scan of Catherine Chun, which he connects to his Omnitool. In Omicron Simon uses another to build a second body for himself using a Haimatsu Power Suit to be able to survive the extreme water pressure of the Omega Sector.
"""


def test_search_local_database_semantic():
    temp_dir = tempfile.mkdtemp()
    try:
        search = SearchLocalDatabaseSemantic(temp_dir, "sentence-transformers/all-MiniLM-L6-v2", 2, NNConfig("cuda:0", 8), {})
        search.update("Dixie Flatline", __DIXIE_FLATLINE_ARTICLE__)
        search.update("Johny Silverhand", __JOHNNY_SILVERHAND_ARTICLE__)
        search.update("Relic", __RELIC_ARTICLE__)
        search.update("Cortex Chip", __CORTEX_CHIP_ARTICLE__)
        construct_search = search.search("Construct")
        rockerboy_search = search.search("Rocker")
        biochip_search = search.search("Bio-Chip")
        cortex_chip_search = search.search("Cortex Chip")
        phrase_search = search.search("Sex, drugs and rock'n'roll")
        construct_search_documents = {item.split(" : ")[0] for item in construct_search}
        rockerboy_search_documents = {item.split(" : ")[0] for item in rockerboy_search}
        biochip_search_documents = {item.split(" : ")[0] for item in biochip_search}
        cortex_chip_search_documents = {item.split(" : ")[0] for item in cortex_chip_search}
        phrase_search_documents = {item.split(" : ")[0] for item in phrase_search}
        assert construct_search_documents == {"Dixie Flatline", "Cortex Chip"}
        assert rockerboy_search_documents == {"Johny Silverhand"}
        assert biochip_search_documents == {"Cortex Chip"}
        assert cortex_chip_search_documents == {"Cortex Chip"}
        assert phrase_search_documents == {"Johny Silverhand"}
    finally:
        shutil.rmtree(temp_dir)
